"""
Constants and configuration variables.
"""

# Log file settings
LOG_INTERVAL_MS = 1000
LOG_FILE_NAME = 'log'

# Are we running on the actual hardware ?
HAS_HARDWARE = True

# Communications Settings
LIVE_DISPLAY_FILE_NAME = 'Communications/html/live.html'

HTTP_HOST = ""
HTTP_PORT = 8080

# Magnetorquer port settings
X_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
X_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
X_AXIS_H_BRIDGE_PWM_PORT_1 = -1
X_AXIS_H_BRIDGE_PWM_PORT_2 = -1

Y_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
Y_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
Y_AXIS_H_BRIDGE_PWM_PORT_1 = -1
Y_AXIS_H_BRIDGE_PWM_PORT_2 = -1

Z_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
Z_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
Z_AXIS_H_BRIDGE_PWM_PORT_1 = -1
Z_AXIS_H_BRIDGE_PWM_PORT_2 = -1