X_AXIS_H_BRIDGE_CONNECTED = False
X_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
X_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
X_AXIS_H_BRIDGE_PWM_PORT_1 = -1
X_AXIS_H_BRIDGE_PWM_PORT_2 = -1

Y_AXIS_H_BRIDGE_CONNECTED = False
Y_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
Y_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
Y_AXIS_H_BRIDGE_PWM_PORT_1 = -1
Y_AXIS_H_BRIDGE_PWM_PORT_2 = -1

Z_AXIS_H_BRIDGE_CONNECTED = False
Z_AXIS_H_BRIDGE_DIRECTION_PORT_1 = -1
Z_AXIS_H_BRIDGE_DIRECTION_PORT_2 = -1
Z_AXIS_H_BRIDGE_PWM_PORT_1 = -1
Z_AXIS_H_BRIDGE_PWM_PORT_2 = -1
